name: publish-version

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: python3 -m pip install -r ./pip-requirements.txt
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.x
          dune-cache: false # can cause trouble when generating melange docs in step below: https://github.com/ocaml/dune/issues/7720
      - name: Install all deps
        run: make install
      - name: Generate melange docs
        run: opam reinstall -y melange --with-doc
      - name: Copy melange docs
        run: cp -r _opam/.opam-switch/build/melange.dev/_build/default/_doc/_html docs
      - name: Check Reason syntax
        run: make check-reason
      - name: Build playground
        run: make build-playground
      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - run: git fetch origin gh-pages --depth=1
      - run: mike deploy ${{  github.ref_name }}
      - run: mike set-default --push ${{  github.ref_name }}
